{% set name = "lxml-stubs" %}
{% set version = "0.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lxml-stubs-{{ version }}.tar.gz
  sha256: 184877b42127256abc2b932ba8bd0ab5ea80bd0b0fee618d16daa40e0b71abee

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  # Import test is done in run_test.py due to - character in package name.
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/lxml-stubs/
  summary: Type annotations for the lxml package
  license_file: LICENSE
  license: Apache-2.0

extra:
  recipe-maintainers:
    - thewchan
