{% set name = "lxml-stubs" %}
{% set version = "0.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lxml-stubs-{{ version }}.tar.gz
  sha256: 9c71dd1893698dd2ccb1e190fabbd5b906daf910c7605147f3a3b3cea21b7c64

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  # Import test is done in run_test.py due to - character in package name.
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/lxml-stubs/
  summary: Type annotations for the lxml package
  license_file: LICENSE
  license: Apache-2.0

extra:
  recipe-maintainers:
    - thewchan
